name: Daily Crime Data Upload

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 8:00 AM ET (12:00 UTC)
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run daily pipeline
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python daily_pipeline.py
